name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `master` branch
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
        
      - name: Install, build, and upload your site
        uses: withastro/action@v2
        with:
          path: . # Das Stammverzeichnis Ihres Astro-Projekts im Repository.
          node-version: 20 # Die spezifische Version von Node, die zum Erstellen Ihrer Site verwendet werden soll.
          package-manager: npm@latest # Der Node-Paketmanager, der zum Installieren von Abhängigkeiten und zum Erstellen Ihrer Site verwendet werden soll.

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 